project:
  type: book
  output-dir: _site

book:
  title: "Practical One"
  chapters:
    - index.qmd
    - prac1.qmd
    - prac2.qmd
    - prac4.qmd
  navbar: false

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-fold: false
    html-math-method: katex
