project:
  type: book
  output-dir: _output

book:
  title: "Practical One"
  chapters:
    - index.qmd
    - q1.qmd
    - q2.qmd
    - q3.qmd
    - q4.qmd
  navbar: false

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-fold: false
    html-math-method: katex
