---
title: "Question 4"
---

## Confirm Beta estimate by fitting model

Check the same β estimates as when fitting the linear regression model using lm() in R.

**Code**
```{r}
#| echo: false
####### Create design matrix ####### 
Y <-cars$dist

intercept<- rep(1, length(Y))

X <- cbind(intercept,cars$speed)

#######  Function Calculates Beta hat and Std Error ####### 

calculate<-function(X, Y){
  
  # Solve for beta hat
  beta_hat <- solve(t(X) %*% X) %*% t(X)%*% Y
  
  # Calculate Std Errors
  Sxx <- sum((X[,2] - mean(X[,2]))^2)
  Sxy <- sum((X[,2] - mean(X[,2])) * (Y - mean(Y)))
  
  predictions <- beta_hat[1]+beta_hat[2]*X[,2]
  residuals <- Y-predictions
  rse <- sqrt(sum(residuals^2)/(length(Y)-2))
  
  se_intercept<- rse*sqrt(1/length(Y)+mean(X[,2])^2/Sxx)
  se_speed <- rse/ sqrt( Sxx)
  
  std_error <- matrix(0, 2, 1) 
  std_error[1,1] <- se_intercept
  std_error[2,1] <- se_speed
  
  return( list("coefficients" = c(beta_hat[1], beta_hat[2]), 
               "std error" = c(se_intercept, se_speed)))
}

```
```{r}
####### Calculate Beat values and Standard Error ####### 
answer <- calculate(X, Y)

####### Fit Model ####### 
model <- lm(dist ~ speed, data = cars)

# Print coefficients
print(answer$coefficients)   
print(model$coefficients) 


# Corrected comparison
message_1 <-ifelse (all(round(answer$coefficients,4) ==
                        round(model$coefficients,4)),
                        "The coefficients are the same!"
                        ,"The coefficients differ.")

message_2 <-ifelse (all(round(answer$`std error`,4) ==
                        round(summary(model)$coefficients[, "Std. Error"],4)),
                        "The standard errors are the same!",
                        "The tandard errors differ.")

```

**Answer if beta coefficients are correct**

```{r}
#| echo: false
message_1
```

**Answer if standard errors are correct**

```{r}
#| echo: false
message_2
```